Upgrade and edit functionality
deltaDAO/nautilus-examples pull request #6
Opened 2024-02-15 22:52 UTC by moritzkirstein

Fixes #

## Proposed Changes

  -
  -
  -

2024-04-01 15:17 UTC, Abrom8 requested changes

2024-04-01 15:17 UTC, Abrom8 commented on README.md
> +   > The account needs to be funded with tokens. Depending on the example and network either `matic` (`mumbai`) or `gx` (`genx`, `pontusx`) for the network fees and `EUROe` or `OCEAN` for paid servic
blocking: Pontus-X does not use `gx` fee tokens.

2024-04-01 15:17 UTC, Abrom8 commented on config.ts
> +  },
question: Are these the correct addresses?

2024-04-01 15:17 UTC, Abrom8 commented on index.ts
> +  await editServiceOffering(nautilus)
nitpick: Comment out, maybe comment simple publish in.

2024-04-18 13:16 UTC, moritzkirstein commented on edit.ts
> +    //     .build()
refactored to provide more examples

2024-04-19 14:58 UTC, Abrom8 approved these changes

2024-04-19 14:58 UTC, merged